### ISSUE TITLE
Problem with GeoJSON data while adding new feature using Oskari.mapframework.bundle.mapmodule.request.AddFeaturesToMapRequest

### ISSUE THREAD

**Issue by an9l** [nls-oskari/oskari#24]
While adding a new feature for geometryType 'GeoJSON', the attributes passed as parameter is not stored in feature being created.

**Comment by ZakarFin** [comment]
This has been fixed in the next version (1.34). The request has been changed a bit since only the geometry is required and all optional flags have been moved to an options object in the request. Here's the latest documentation for the feature requests:
http://oskari.org/documentation/requests/addfeaturestomaprequest
http://oskari.org/documentation/requests/removefeaturesfrommaprequest

**Comment by ZakarFin** [comment]
1.34 (and the fix) has been released so closing this.
