### ISSUE TITLE
Styling is missing for geometryType 'WKT', while adding feature to map.

### ISSUE THREAD

**Issue by an9l** [nls-oskari/oskari#25]
The style being passed as parameter, while adding feature to map using AddFeaturesToMapRequest for geometryType 'WKT', is not applied to the map. The problem seems to be in 'VectorLayerPlugin.js', where feature.length seems to be undefined, which prohibited in setting style for feature.

**Comment by ZakarFin** [comment]
The request API will be change a bit in the upcoming 1.34 release. The style should be passed as a generic style object instead of Openlayers.Style instance to make it work with different map-engines (ol3 for example).

**Comment by ZakarFin** [comment]
This has been fixed in version 1.34, but the style is no longer sent as an Openlayers2 object and as such the options for styling are currently limited. Let me know if this there's some additional styling that should be part of the style handling: http://oskari.org/documentation/requests/addfeaturestomaprequest. 

Parts that are parsed from the style object can be found here:
https://github.com/nls-oskari/oskari/blob/master/bundles/mapping/mapmodule/plugin/vectorlayer/VectorLayerPlugin.ol2.js#L350-L369
