### ISSUE TITLE
Error when running index.html 

### ISSUE THREAD

**Issue by mfarook** [nls-oskari/oskari#33]
I am following this for understanding frontend development http://www.oskari.org/guides/quick-start/my-first-bundle. I had downloaded the source and extracted and run /applications/sample/myfirst/index.html from netbeans IDE as mentioned. I am getting an error 
Unable to load appsetupconfig
Uncaught Error: Couldn't start bundle with id mapfull. Error was: Class "Oskari.userinterface.component.PopupService" does not exist(…)

**Comment by ZakarFin** [comment]
Sorry about that. I just fixed and simplified the sample apps on the develop branch: https://github.com/nls-oskari/oskari/commit/645415800036f04166e5db2b824322f2f2794805.

The problem was that there is no real dependency management implemented and one of the bundles (framework/ui-components) that provides the PopupService was not loaded (was not referenced in appsetup.json).

**Comment by ZakarFin** [comment]
Also updated the creating you own bundle documentation a bit: https://github.com/nls-oskari/oskari.org/commit/731c35f3024a663d4061882f8e69395ccac17222

The page on oskari.org should update shortly

**Comment by mfarook** [comment]
Thanks for the update and fix.
